### ISSUE TITLE
NNNN base in my haplotype and --n-fraction option

### ISSUE THREAD

**Issue by FabienMbaya** [bluenote-1577/devider#1]
--n-fraction <x> Customizing and operating this option in the running command is impossible. 
I found this tool more interesting. To avoid NNNN base in my haplotype, I would like to customize this option to my data.

Could you give me help?

**Comment by bluenote-1577** [comment]
@FabienMbaya You should be able to set --n-fraction to 0 if you want to avoid NNN bases. Let me know if it works.

**Comment by FabienMbaya** [comment]
Thank you for your prompt reply.

I tried the following command scripts, but the NNN still remain in the halotypes yield:

devider --n-fraction 0 --bam-file my_bam_file.bam --vcf-file my_variants.vcf -r my_reference.fasta -o ./devider_output/ 

devider --bam-file my_bam_file.bam --vcf-file my_variants.vcf -r my_reference.fasta --n-fraction 0 -o ./devider_output/ 

devider --bam-file my_bam_file.bam --vcf-file my_variants.vcf -r my_reference.fasta -o ./devider_output/sample --n-fraction 0 

Do you have any tips?

**Comment by bluenote-1577** [comment]
It looks like I added a condition: if the coverage of the base is < --min-cov, then N is output. So if there is a deletion when mapping against the reference, or you have very low coverage, it will spit out N.

Consider adjusting --min-cov to something like 1. Do not set it to 0 -- the results would be bad inaccurate.

**Comment by FabienMbaya** [comment]
Thank you very much for your help, it works well.
